### ISSUE TITLE
DS2 T5 model is released now

### ISSUE THREAD

**Issue by jshin49** [Yushi-Hu/IC-DST#1]
Dear authors, 

I saw that your paper experimented with our code so quickly, and I'm very happy to see such great progress from your work.

I released the T5 versions recently so if you want to compare it on 2.4, you can check our repository for the updates.

Note that our code used the 40GB NVIDIA Tesla A100 GPU (single GPU) to fine-tune the T5-large model so it may not work well with DDP with smaller ones, as we did not try.

Please let me know if there are any issues. 

p.s. if you could modify the citations to the bibtex I posted in the code, that would be also much appreciated!

Best,
Jay

**Comment by Yushi-Hu** [comment]
Thanks for letting us know! We will update the numbers and the bibtex in later versions of this paper
